import controle
controle.check_housenumber_5000_9000()
controle.check_housenumber_number_null()
controle.check_housenumber_number_0()
controle.check_housenumber_number_format()
controle.check_housenumber_without_postcode()
controle.check_housenumber_same_ordinal()
controle.check_housenumber_ordinal_format()
controle.check_group_name_format()
controle.check_group_kind()
controle.check_group_same_name()
